### ISSUE TITLE
Encoding a VP9 stream results in GPU hang on SKL if the hybrid codec is enabled too

### ISSUE THREAD

**Issue by xhaihao** [01org/intel-vaapi-driver#46] opened 2017-02-14 06:42 UTC
steps to reproduce the issue:
1. Install intel-hybrid-driver
2. build intel-vaapi-driver with --enable-hybrid-codec
3. build libyami with --enable-vp9enc
4. run the following command on SKL
yamitranscode -W xxx -H xxx -i <yuvfile> -i  -c vp9 -o <vp9 file>

**Comment by yakuizhao** [comment] 2017-02-14 07:00
I agree that the driver should add more check for the invalid input.

In fact the issue is also related with that the upper-middleware doesn't check the returned Profile/Entrypoint. Instead it directly passes the invalid parameter.
But unfortunately this is not checked in the driver.

**Closed** 2017-02-14 07:28 UTC
Labels: bug, in progress
