### ISSUE TITLE
vaapi compiling issue error: 'struct VADriverVTableWayland' has no member named 'has_prime_sharing'

### ISSUE THREAD

**Issue by kvpramod91** [01org/intel-vaapi-driver#243] opened 2017-08-04 05:12 UTC
i965_output_wayland.c: In function 'va_GetSurfaceBufferWl':
i965_output_wayland.c:267:16: error: 'struct VADriverVTableWayland' has no member named 'has_prime_sharing'
     if (!vtable->has_prime_sharing || (drm_intel_bo_gem_export_to_prime(obj_surface->bo, &fd) != 0)) {
                ^

 wget https://launchpad.net/ubuntu/+archive/primary/+files/intel-vaapi-driver_1.8.3.orig.tar.bz2
./autogen.sh
./configure
make
am facing the above mentioned issue 

Downloaded the libva from
 git clone https://github.com/01org/libva.git
./autogen.sh
./configure
make 
make install
Updated the latest libva version 
libva info: VA-API version 0.40.0

**Comment by xhaihao** [comment] 2017-08-04 05:21
A duplicate of https://github.com/01org/intel-vaapi-driver/issues/218

**Closed by xhaihao** 2017-08-04 05:21 UTC
